<?xml version="1.0" encoding="UTF-8" ?><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- 
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="css/layout.css" media="all" rel="stylesheet" type="text/css" />
</head>
-->

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title></title><link href="css/layout.css" media="screen" rel="stylesheet" type="text/css" ></head>

<body>
<div id="pageWrapper"> 
  <div id="header"> 
    <p>#header</p>
  </div>
  <div id="nav"> 
    <p>#nav</p>
  </div>
  <div id="sidebar"> 
    <div id="subNav"> 
      <p>#subNav</p>
    </div>
    <div id="adminMenu"> 
      <p>#adminMenu</p>
    </div>
    <div id="userForm"> 
      <p>#userForm</p>
    </div>
    <p>#sidebar</p>
  </div>
  <div id="main"> 
    <p>#main</p>
  </div>
  <div id="footer"> 
    <p>#footer</p>
  </div>
</div>
CHAPTER 2 DESIGNING YOUR SITE 24 
</body>
</html>