<?php if ($this->pageCount) {
    // you need to add each of the request parameters to url
    $params = Zend_Controller_Front::getInstance()->getRequest()->getParams();
    // remove the system parameters
    unset($params['module']);
    unset($params['controller']);
    unset($params['action']);
	
	/*--
	1. request param. contains form parameters and causes incorrect paginator controls on usage of _forward command on url()
	---
	Fix: $params1 array created, and manual route for default/bug/list
	Fix. dt: 20110311_0000
	Author: nats
	--*/
	$params1['module'] = 'default';
	$params1['controller'] = 'bug';
	$params1['action'] = 'list';
?>

<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)) { ?>
<a href="<?php echo $this->url(array_merge($params1, array('page' => $this->
        previous))); ?>">
&lt; Previous
</a> |
<?php } else { ?>
<span class="disabled">&lt; Previous</span> |
<?php } ?>
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page) { ?>
<?php if ($page != $this->current) { ?>
<a href="<?php echo $this->url(array_merge($params1, array('page' => $page))); ?>">
<?php echo $page; ?>
</a> |
<?php } else { ?>
<?php echo $page; ?> |
<?php }
    } ?>
<!-- Next page link -->
<?php if (isset($this->next)) { ?>
<a href="<?php echo $this->url(array_merge($params1, array('page' => $this->next))); ?>">
Next &gt;
</a>
<?php } else { ?>
<span class="disabled">Next &gt;</span>
<?php } ?>
</div>
<?php } ?>